version: '3.4'

services:
  app:
    container_name: 'app'
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      ports:
      - 3000:3000
      stdin_open: true
      envoirnment:
        - PORT=3000
      command: npm run dev
volume:
  node_modules: